# Generated by Django 3.1.3 on 2021-02-21 03:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tweet', '0002_notification'),
    ]

    operations = [
        migrations.AddField(
            model_name='tweets',
            name='offend_score',
            field=models.FloatField(default=0.0),
        ),
    ]
