# Generated by Django 3.1.3 on 2021-02-20 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User', '0002_auto_20210220_0948'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Unkonwn', max_length=15),
        ),
    ]
